export const books = [
  {
    id: 9788203190195,
    title: 'Snømannen',
    author: 'Jo Nesbø',
    price: 199,
    description: 'Harry Hole jakter på en seriemorder som etterlater snømenn',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 2007,
    condition: 'very-good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788202401239,
    title: 'Harry Potter og De vises stein',
    author: 'J.K. Rowling',
    price: 249,
    description: 'Den unge trollmannen Harry oppdager sin magiske arv',
    signed: 'signed',
    binding: 'hardcover',
    language: 'norwegian',
    genre: 'fantasy',
    publishedYear: 1997,
    condition: 'like-new',
    stock: 12,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'barn',
  },
  {
    id: 9788203365562,
    title: 'Rødstrupe',
    author: 'Jo Nesbø',
    price: 189,
    description: 'En pensjonert politimann blir involvert i et gammelt mordmysterium',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 2000,
    condition: 'good',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203192632,
    title: 'Sult',
    author: 'Knut Hamsun',
    price: 129,
    description: 'En sultende forfatters psykologiske kamp i Kristiania',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 1890,
    condition: 'acceptable',
    stock: 3,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203225001,
    title: 'Beatles',
    author: 'Lars Saabye Christensen',
    price: 179,
    description: 'Fire gutters vennskap gjennom 1960-årene i Oslo',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 1984,
    condition: 'good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788202225076,
    title: 'Naiv.Super.',
    author: 'Erlend Loe',
    price: 149,
    description: 'En 25-årings søken etter mening i livet',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 1996,
    condition: 'very-good',
    stock: 10,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203367900,
    title: 'Morgendagens sang',
    author: 'Maja Lunde',
    price: 219,
    description: 'Klimakvartettens andre bok om bier og mennesker',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 2017,
    condition: 'like-new',
    stock: 6,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203291472,
    title: 'Bienes historie',
    author: 'Maja Lunde',
    price: 229,
    description: 'Tre historier om bier som knytter sammen fortid, nåtid og fremtid',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 2015,
    condition: 'good',
    stock: 4,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203192403,
    title: 'Min kamp 1',
    author: 'Karl Ove Knausgård',
    price: 239,
    description: 'Første bind i den självbiografiske romanserien',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'biography',
    publishedYear: 2009,
    condition: 'very-good',
    stock: 3,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203364428,
    title: 'Hvite niggere',
    author: 'Olavo de Carvalho',
    price: 169,
    description: 'Politisk filosofi og samfunnskritikk',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'history',
    publishedYear: 1990,
    condition: 'acceptable',
    stock: 2,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203367801,
    title: 'Kodetidsrom',
    author: 'Johan Harstad',
    price: 259,
    description: 'Science fiction om tid og rom',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'norwegian',
    genre: 'scifi',
    publishedYear: 2013,
    condition: 'like-new',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203365630,
    title: 'Kvinnen i mitt liv',
    author: 'Vigdis Hjorth',
    price: 179,
    description: 'Familiedrama og konflikter',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 2011,
    condition: 'good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203364473,
    title: 'Heksejakten',
    author: 'Camilla Läckberg',
    price: 199,
    description: 'Krim fra den svenske vestkysten',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 2002,
    condition: 'very-good',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203364497,
    title: 'Piken som elsket hunde',
    author: 'Camilla Läckberg',
    price: 189,
    description: 'Krim med rot i Spania',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 2007,
    condition: 'good',
    stock: 6,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203365517,
    title: 'Ildbarn',
    author: 'Anne Holt',
    price: 209,
    description: 'Krim med psykologisk dybde',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 2004,
    condition: 'very-good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203365500,
    title: 'Blind gudinne',
    author: 'Anne Holt',
    price: 199,
    description: 'Første bok om hanne wilhelmsen',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'crime',
    publishedYear: 1993,
    condition: 'good',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788201165562,
    title: 'Fjellet',
    author: 'Tomas Espedal',
    price: 169,
    description: 'En manns reise inn i naturen og seg selv',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'fiction',
    publishedYear: 2006,
    condition: 'acceptable',
    stock: 3,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203365586,
    title: 'Udyret',
    author: 'Unni Lindell',
    price: 159,
    description: 'Psykologisk thriller',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'thriller',
    publishedYear: 1998,
    condition: 'good',
    stock: 4,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9788203365609,
    title: 'Stjernesøsken',
    author: 'Maria Parr',
    price: 149,
    description: 'Barnebok om vennskap og eventyr',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'norwegian',
    genre: 'children',
    publishedYear: 2012,
    condition: 'like-new',
    stock: 15,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'barn',
  },
  {
    id: 9788203365623,
    title: 'Tonje Glimmerdal',
    author: 'Maria Parr',
    price: 139,
    description: 'Barnebok om en jentes liv i dalen',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'norwegian',
    genre: 'children',
    publishedYear: 2009,
    condition: 'very-good',
    stock: 12,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'barn',
  },
  {
    id: 9780008123208,
    title: 'Døden på Nilen',
    author: 'Agatha Christie',
    price: 169,
    description: 'Poirot løser et mord på en nile-cruise',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'crime',
    publishedYear: 1937,
    condition: 'acceptable',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780008129583,
    title: 'Mord i Orientekspressen',
    author: 'Agatha Christie',
    price: 159,
    description: 'Poirots mest berømte sak',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'crime',
    publishedYear: 1934,
    condition: 'good',
    stock: 10,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780450040184,
    title: 'The Shining',
    author: 'Stephen King',
    price: 179,
    description: 'En familie på et hjemsøkt hotell',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'skrekk',
    publishedYear: 1977,
    condition: 'good',
    stock: 6,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780450411434,
    title: 'It',
    author: 'Stephen King',
    price: 239,
    description: 'En ond klovn terroriserer en by',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'skrekk',
    publishedYear: 1986,
    condition: 'very-good',
    stock: 4,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780451169528,
    title: 'Misery',
    author: 'Stephen King',
    price: 189,
    description: 'En forfatter holdes fanget av sin største fan',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'thriller',
    publishedYear: 1987,
    condition: 'good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780547928227,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    price: 219,
    description: "Bilbo Baggins' eventyr til Ensomfjellet",
    signed: 'signed',
    binding: 'hardcover',
    language: 'english',
    genre: 'fantasy',
    publishedYear: 1937,
    condition: 'like-new',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780544003415,
    title: 'Lord of the Rings',
    author: 'J.R.R. Tolkien',
    price: 349,
    description: 'Hele trilogien i én bok',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'fantasy',
    publishedYear: 1954,
    condition: 'very-good',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780307474278,
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    price: 199,
    description: 'Robert Langdon løser et religiøst mysterium',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'thriller',
    publishedYear: 2003,
    condition: 'good',
    stock: 11,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9781416524793,
    title: 'Angels & Demons',
    author: 'Dan Brown',
    price: 189,
    description: 'Første bok om Robert Langdon',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'thriller',
    publishedYear: 2000,
    condition: 'good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780307949486,
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    price: 209,
    description: 'Journalist og hacker løser et gammelt forsvinning',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'crime',
    publishedYear: 2005,
    condition: 'very-good',
    stock: 10,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780451524935,
    title: '1984',
    author: 'George Orwell',
    price: 149,
    description: 'Dystopisk roman om overvåkning',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1949,
    condition: 'good',
    stock: 14,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780451526342,
    title: 'Animal Farm',
    author: 'George Orwell',
    price: 129,
    description: 'Allegori om revolusjon og korrupsjon',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1945,
    condition: 'acceptable',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780141439518,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    price: 159,
    description: 'Romantisk klassiker fra 1800-tallet',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'romance',
    publishedYear: 1813,
    condition: 'good',
    stock: 12,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780060935467,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 169,
    description: 'Vokseopp-roman om rasisme i Alabama',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1960,
    condition: 'very-good',
    stock: 11,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780743273565,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 149,
    description: 'Amerikansk klassiker om 1920-tallets overflod',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1925,
    condition: 'good',
    stock: 13,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780375704024,
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    price: 199,
    description: 'Kjærlighetsroman i 1960-tallets Tokyo',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1987,
    condition: 'very-good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9781400079278,
    title: 'Kafka on the Shore',
    author: 'Haruki Murakami',
    price: 219,
    description: 'Magisk realisme og filosofisk reise',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'fiction',
    publishedYear: 2002,
    condition: 'good',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780062315007,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 179,
    description: 'Spirituelle reise etter en persons legende',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1988,
    condition: 'very-good',
    stock: 15,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780156027328,
    title: 'Life of Pi',
    author: 'Yann Martel',
    price: 189,
    description: 'Gutt overlever skipsforlis med en tiger',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 2001,
    condition: 'good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780307588371,
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    price: 199,
    description: 'Psykologisk thriller om et forsvinning',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'thriller',
    publishedYear: 2012,
    condition: 'very-good',
    stock: 10,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9781250301697,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    price: 209,
    description: 'Psykologisk thriller om en taus kvinne',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'thriller',
    publishedYear: 2019,
    condition: 'like-new',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780735219090,
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    price: 219,
    description: 'Mysterie og vokseopp-roman',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'fiction',
    publishedYear: 2018,
    condition: 'very-good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780399590504,
    title: 'Educated',
    author: 'Tara Westover',
    price: 199,
    description: 'Memoar om å vokse opp uten skolegang',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'biography',
    publishedYear: 2018,
    condition: 'good',
    stock: 6,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780385490818,
    title: "The Handmaid's Tale",
    author: 'Margaret Atwood',
    price: 179,
    description: 'Dystopisk roman om kvinners undertrykkelse',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1985,
    condition: 'very-good',
    stock: 11,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780553103540,
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    price: 249,
    description: 'Første bok i A Song of Ice and Fire',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'fantasy',
    publishedYear: 1996,
    condition: 'good',
    stock: 5,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780441172719,
    title: 'Dune',
    author: 'Frank Herbert',
    price: 229,
    description: 'Science fiction-klassiker om Arrakis',
    signed: 'unsigned',
    binding: 'hardcover',
    language: 'english',
    genre: 'scifi',
    publishedYear: 1965,
    condition: 'very-good',
    stock: 4,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780553293357,
    title: 'Foundation',
    author: 'Isaac Asimov',
    price: 189,
    description: 'Science fiction om et galaktisk imperiums fall',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'scifi',
    publishedYear: 1951,
    condition: 'good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780060850524,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    price: 159,
    description: 'Dystopisk klassiker om teknologisk samfunn',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'scifi',
    publishedYear: 1932,
    condition: 'acceptable',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780143058144,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    price: 179,
    description: 'Psykologisk roman om mord og skyld',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1866,
    condition: 'good',
    stock: 6,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780316769488,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    price: 169,
    description: 'Tenåringens opprør mot voksenverdenen',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1951,
    condition: 'very-good',
    stock: 12,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
  {
    id: 9780147514011,
    title: 'Little Women',
    author: 'Louisa May Alcott',
    price: 149,
    description: 'Fire søstres liv under og etter borgerkrigen',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1868,
    condition: 'good',
    stock: 10,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'barn',
  },
  {
    id: 9780141439846,
    title: 'Dracula',
    author: 'Bram Stoker',
    price: 169,
    description: 'Klassisk skrekkroman om vampyren grev Dracula',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'skrekk',
    publishedYear: 1897,
    condition: 'acceptable',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780141439471,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    price: 159,
    description: 'Vitenskapsmann skaper et monster',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'skrekk',
    publishedYear: 1818,
    condition: 'good',
    stock: 8,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780141439570,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    price: 149,
    description: 'Roman om skjønnhet, moral og korrupsjon',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'fiction',
    publishedYear: 1890,
    condition: 'very-good',
    stock: 9,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780141439556,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    price: 159,
    description: 'Mørk kjærlighetshistorie på de engelske heiene',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'romance',
    publishedYear: 1847,
    condition: 'good',
    stock: 7,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'voksen',
  },
  {
    id: 9780141441146,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    price: 169,
    description: 'Orphans vokseopp og romantiske eventyr',
    signed: 'unsigned',
    binding: 'pocket',
    language: 'english',
    genre: 'romance',
    publishedYear: 1847,
    condition: 'very-good',
    stock: 11,
    imageUrl: 'https://picsum.photos/400/500',
    ageGroup: 'ungdom',
  },
]
